### ISSUE TITLE
crashes upon every generation, ill never find love

### ISSUE THREAD

**Issue by spearphishing** [88fear/GirlfriendGenerator#1]

**Comment by consist01** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOL IMAGINE

**Comment by 88fear** [comment]
That must mean that I am your soulmate, please pop up in my https://discord.com/ direct messages. My tag is nothing other than fear#0007. Please do not fall for any impersonators on the discord platform.

**Comment by incompliant** [comment]
i have found my true love

i am camel#8080 😽
